# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "*.md", 
  ".github/*", 
  "doc/*", 
  "VERSION", 
  "go.sum", 
  "go.sum", 
  ".gitignore", 
  "pkg/api/*",  
  ".devcontainer/*", 
  ".dockerignore", 
  "bin", 
  "config/**", 
  "PROJECT", 
  "api/v1alpha1/*generated*", 
  "internal/k8s/mock_*", 
  "internal/mocks/**", 
  "examples/*", 
  "default-cluster-templates/*",
  "test/README.md"
]
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"