# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.credentialsM2M.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-manager.fullname" . }}-credentials-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-manager.labels" . | nindent 4 }}
data:
  credentials-m2m.sh: |
    #!/bin/bash
    set -euo pipefail
    # Helm values
    VAULT_ADDR="http://{{ .Values.credentialsM2M.vault.service }}:{{ .Values.credentialsM2M.vault.port }}"
    KEYCLOAK_URL="http://{{ .Values.credentialsM2M.keycloak.service }}:{{ .Values.credentialsM2M.keycloak.port }}"
    KEYCLOAK_REALM="{{ .Values.credentialsM2M.keycloak.realm }}"
    CLIENT_ID="{{ .Values.credentialsM2M.keycloak.clientId }}"
    SECRET_PATH="{{ .Values.credentialsM2M.vault.secretPath }}"
    RETRY_ATTEMPTS={{ .Values.credentialsM2M.job.retryAttempts }}
    RETRY_DELAY={{ .Values.credentialsM2M.job.retryDelay }}
    K8S_API_SERVER="https://kubernetes.default.svc"
    K8S_CA_CERT="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    KEYCLOAK_SECRET_NAMESPACE="{{ .Values.credentialsM2M.keycloak.adminSecretNamespace }}"
    KEYCLOAK_SECRET_NAME="{{ .Values.credentialsM2M.keycloak.adminSecretName }}"

    # service account token for Vault authn
    SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

    log() {
        echo "[$(date -Iseconds)] $*" >&2
    }

    retry_with_backoff() {
        local attempt=1
        local cmd_description="$1"  # First argument is description
        shift  # Remove description from arguments, leaving the actual command
        
        log "Starting retry for: $cmd_description (max attempts: $RETRY_ATTEMPTS)"
        
        while [ $attempt -le $RETRY_ATTEMPTS ]; do
            log "Attempting $cmd_description (attempt $attempt/$RETRY_ATTEMPTS)"
            
            if "$@"; then
                log "SUCCESS: $cmd_description completed on attempt $attempt"
                return 0
            fi
            
            if [ $attempt -lt $RETRY_ATTEMPTS ]; then
                log "FAILED: $cmd_description attempt $attempt failed - retrying in ${RETRY_DELAY}s..."
                sleep $RETRY_DELAY
            else
                log "FAILED: $cmd_description attempt $attempt failed - no more retries"
            fi
            
            attempt=$((attempt + 1))
        done
        
        log "ERROR: $cmd_description failed after $RETRY_ATTEMPTS attempts"
        return 1
    }

    authenticate_vault() {
        local auth_response=$(retry_with_backoff "vault authentication" curl -s -f \
            --request POST \
            --data "{\"jwt\": \"$SA_TOKEN\", \"role\": \"cluster-manager\"}" \
            "$VAULT_ADDR/v1/{{ .Values.credentialsM2M.vault.authPath }}/login")

        if [ $? -ne 0 ]; then
            log "ERROR: failed to authn with Vault"
            return 1
        fi

        VAULT_TOKEN=$(echo "$auth_response" | jq -r '.auth.client_token')
        if [ "$VAULT_TOKEN" = "null" ] || [ -z "$VAULT_TOKEN" ]; then
            log "ERROR: failed to extract Vault token"
            return 1
        fi

        return 0
    }

    get_keycloak_admin_password() {
        local secret_response=$(retry_with_backoff "Keycloak admin credentials request" curl -s -f \
            --header "Authorization: Bearer $SA_TOKEN" \
            --cacert "$K8S_CA_CERT" \
            "$K8S_API_SERVER/api/v1/namespaces/$KEYCLOAK_SECRET_NAMESPACE/secrets/$KEYCLOAK_SECRET_NAME")

        if [ $? -ne 0 ]; then
            log "ERROR: failed to get keycloak admin secret from Kubernetes API"
            return 1
        fi

        # Extract and decode base64 password
        local admin_pass_b64=$(echo "$secret_response" | jq -r '.data["admin-password"] // .data.password // empty')
        if [ -z "$admin_pass_b64" ] || [ "$admin_pass_b64" = "null" ]; then
            log "ERROR: password field not found in secret. Available fields:"
            echo "$secret_response" | jq -r '.data | keys[]' >&2
            return 1
        fi

        ADMIN_PASS=$(echo "$admin_pass_b64" | base64 -d)
        if [ -z "$ADMIN_PASS" ]; then
            log "ERROR: failed to decode admin password"
            return 1
        fi

        return 0
    }

    get_keycloak_admin_token() {
        local admin_user="admin"
        if ! get_keycloak_admin_password; then
            log "ERROR: failed to get Keycloak admin password"
            return 1
        fi

        local token_response=$(retry_with_backoff "getting keycloak admin token" curl -s -f \
            --request POST \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data "grant_type=password&client_id=admin-cli&username=$admin_user&password=$ADMIN_PASS" \
            "$KEYCLOAK_URL/realms/master/protocol/openid-connect/token")

        if [ $? -ne 0 ]; then
            log "ERROR: failed to get keycloak admin token"
            return 1
        fi

        KC_ADMIN_TOKEN=$(echo "$token_response" | jq -r '.access_token')
        if [ "$KC_ADMIN_TOKEN" = "null" ] || [ -z "$KC_ADMIN_TOKEN" ]; then
            log "ERROR: failed to extract keycloak admin token"
            return 1
        fi

        return 0
    }

    check_existing_secret() {
        local secret_response=$(curl -s -w "%{http_code}" \
            --header "X-Vault-Token: $VAULT_TOKEN" \
            "$VAULT_ADDR/v1/$SECRET_PATH")

        local http_code="${secret_response: -3}"

        if [ "$http_code" = "200" ]; then
            return 0
        elif [ "$http_code" = "404" ]; then
            log "secret not found, proceeding with extraction"
            return 1
        else
            log "ERROR: response code $http_code when checking vault secret"
            return 1
        fi
    }

    extract_client_credentials() {
        # get client UUID
        local clients_response=$(retry_with_backoff "extract client cred" curl -s -f \
            --header "Authorization: Bearer $KC_ADMIN_TOKEN" \
            --header "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients?clientId=$CLIENT_ID")

        if [ $? -ne 0 ]; then
            log "ERROR: failed to get client list from keycloak"
            return 1
        fi

        local client_uuid=$(echo "$clients_response" | jq -r ".[0].id")
        if [ "$client_uuid" = "null" ] || [ -z "$client_uuid" ]; then
            log "ERROR: co-manager-m2m-client not found in keycloak"
            return 1
        fi

        # get client secret
        local secret_response=$(retry_with_backoff "get client secret" curl -s -f \
            --header "Authorization: Bearer $KC_ADMIN_TOKEN" \
            --header "Content-Type: application/json" \
            "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients/$client_uuid/client-secret")

        if [ $? -ne 0 ]; then
            log "ERROR: failed to get client secret from keycloak"
            return 1
        fi

        CLIENT_SECRET=$(echo "$secret_response" | jq -r '.value')
        if [ "$CLIENT_SECRET" = "null" ] || [ -z "$CLIENT_SECRET" ]; then
            log "ERROR: failed to extract client secret"
            return 1
        fi

        return 0
    }

    store_credentials_in_vault() {
        local vault_data=$(jq -n \
            --arg client_id "$CLIENT_ID" \
            --arg client_secret "$CLIENT_SECRET" \
            '{data: {client_id: $client_id, client_secret: $client_secret}}')

        local store_response=$(curl -s -w "HTTPSTATUS:%{http_code}" \
            --request PUT \
            --header "X-Vault-Token: $VAULT_TOKEN" \
            --header "Content-Type: application/json" \
            --data "$vault_data" \
            "$VAULT_ADDR/v1/$SECRET_PATH")

        local http_code=$(echo "$store_response" | grep -o "HTTPSTATUS:[0-9]*" | cut -d: -f2)
        if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            log "SUCCESS: credentials stored in vault at $SECRET_PATH"
            return 0
        else
            log "ERROR: failed to store credentials in vault (HTTP $http_code)"
            return 1
        fi
    }

    main() {
        if ! authenticate_vault; then
            log "FATAL: vault authn failed"
            exit 1
        fi

        if check_existing_secret; then
            log "job completed successfully"
            exit 0
        fi

        if ! get_keycloak_admin_token; then
            log "FATAL: failed to get keycloak admin token"
            exit 1
        fi

        if ! extract_client_credentials; then
            log "FATAL: failed to extract client credentials"
            exit 1
        fi

        if ! retry_with_backoff "store cred in vault" store_credentials_in_vault; then
            log "FATAL: failed to store credentials in vault"
            exit 1
        fi

        log "job completed successfully"
    }

    main "$@"
{{- end }}
