# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.metrics.service.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "templateController.serviceMonitorLabels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      {{- .Values.metrics.serviceMonitor.labels | nindent 6 }}

apiVersion: v1
kind: Service
metadata:
  name: clusters-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- .Values.metrics.service.labels.clusterManager | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    app: "{{.Chart.Name}}-cm"

apiVersion: v1
kind: Service
metadata:
  name: templates-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- .Values.metrics.service.labels.templateController | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    app: "{{.Chart.Name}}-controller"
{{- end -}}
