# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Secret with Kubernetes standard pod security admission configuration that applies to all namespaces except kube-system.
# https://kubernetes.io/docs/concepts/security/pod-security-admission/
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-security-admission-config
stringData:
  baseline.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1beta1
          kind: PodSecurityConfiguration
          defaults:
            enforce: "baseline"
            enforce-version: "latest"
            audit: "baseline"
            audit-version: "latest"
            warn: "baseline"
            warn-version: "latest"
          exemptions:
            usernames: []
            runtimeClasses: []
            namespaces: [kube-system]
  privileged.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1beta1
          kind: PodSecurityConfiguration
          defaults:
            enforce: "privileged"
            enforce-version: "latest"
            audit: "privileged"
            audit-version: "latest"
            warn: "privileged"
            warn-version: "latest"
          exemptions:
            usernames: []
            runtimeClasses: []
            namespaces: [kube-system]
  restricted.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1beta1
          kind: PodSecurityConfiguration
          defaults:
            enforce: "restricted"
            enforce-version: "latest"
            audit: "restricted"
            audit-version: "latest"
            warn: "restricted"
            warn-version: "latest"
          exemptions:
            usernames: []
            runtimeClasses: []
            namespaces: [kube-system]
type: Opaque