# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-manager.fullname" . }}
  labels:
    app: "{{.Chart.Name}}-cm"
spec:
  selector:
    app: "{{.Chart.Name}}-cm"
  type: {{ .Values.clusterManager.service.type }}
  ports:
    - name: rest
      port: {{ .Values.clusterManager.service.rest.port }}
      targetPort: {{ .Values.clusterManager.service.rest.port }}
      protocol: TCP

{{- if .Values.openpolicyagent.enabled -}}
{{- if .Values.service.opa.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-manager.fullname" . }}-opa
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "cluster-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.opa.type }}
  ports:
    - port: {{ .Values.service.opa.port }}
      targetPort: {{ .Values.service.opa.port }}
      protocol: TCP
      name: opa
  selector:
    {{- include "cluster-manager.selectorLabels" . | nindent 4 }}
{{- end}}
{{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-template-controller"
  labels:
    app.kubernetes.io/name: "{{.Release.Name}}-template-controller"
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - name: http-health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: "{{.Chart.Name}}-controller"
