# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
