// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9a1fbuLZ/Rddn1ip0YscJKS3c1cVlgLY5nQEu0M49h+R0KfZOosGRPJIcmjL573dJ",
	"8jNxEofX0Md8KLH12ntrv7XlubE8NgoZBSqFtXtjhZjjEUjg+mnfk2QMp5z9AZ5s++8A+8BVA3zGozAA",
	"a9fafvECb7/aadqt5ivXbnlbL+2dl72GvdVobDew5/Z2dsCqWYRau9bQjK9ZFI/UWDN9aKYnvlWzOPwZ",
	"EQ6+tSt5BDVLeEMYYbVin/ERltauFUW6p5yEagohOaEDazqdqsEiZFSABr3luvYv2D+DPyMQUr3xGJVA",
	"9U8chgHxsCSM1v8QjKp32VI/cehbu9Y/6hlp6qZV1E856wUwOgSJSSDMuj4Ij5NQzWbtWic9hQ0iFIV4",
	"EjDsIyIQZRKFnIXAgwlSqEQBluAjxnUTB/MoGZJDQCOQQ+Y71rRmtdyG/YHiSA4ZJ18UYR4Nkf1IDoHK",
	"eHpEqNkC/VugERGC0IHCgNAxDkgCb8s+ZvINi+hjwnrMEAfBIu6BAq6vlkdYamp+OGvHoO3YB4z2A+I9",
	"Jj/EHIg8FgW+3u0eKF7wQAjwFZ8oIL2Ic6ASCYklINbXLxOUNPgvXNduUwmc4uAc+Bj4EeeMPyImF0MN",
	"+Jj4wBWVY5iDCYoo7gWg2HeIqa9+aegN4n6kW7BiIQM+Ag25Rqqh2KWtlMkIqHxUBr/IgFSiGAJPuVtt",
	"E8mAciw1Op5ZLXwQREICN5O3aZ9p3akFXBKjgBQSnAWnAaZwBtifrAL4LVDgxDuXWEZCEYfQPsdC8siT",
	"Eb/lHFdRDzgFCeIjcEEMAWd0Z80KcA8CkWtiWonpJtIHb+IFcDrEAtZe32j6kiUp8+Ed4EAO15+T+YbE",
	"RMJIrBp+zHzQOzStWSP8uW3GNFzXTY0I5hxPVHvC3fFa6wImYRQqRV6C8LQ2T9qYiX6wz+Ozz/9GmEoi",
	"JwVfpqEZhIyikeaPmjUi1DxlrKJU2AD4nZllCT/8mlKzyBEZlbHvE6WpcHBa6FGirrFUKle5HFon6znQ",
	"GAcRCAfpldAVTJJ+AmEOSFtz7Y9ggULMZWaPjEY3Sl45ciP8+VegA7UL21s1K57G2rX+89Nf/7nE9pd9",
	"+9+uvdPNfjp293mu4ad5V25WTRt6aMiuYFLXwKMQEy6QHGKJKBjPyWPaQ9FWSMpQ7NbrGfs6hNV95om6",
	"x6gHoRR1NgY+JnBdv2b8itCBfU3k0Da7IeqG2PV/iAmV+LONqW97Q8yxJ4HbAqRVy/jmxvKpcETUc3w2",
	"woTWr2BiN61dS4NqNx01s+MzKayapdoaaVvDmmeEacYK5yF4XwEjOD844UE4IdN/D0Pd9Q2pZsgKhjRv",
	"CVfCruDbuLTjX8+TV5t7G52Os7TD5vMSvKb5MPIyRrK7WN+eR6MR5pN5OYPEv54XJxqNesCVOHhmkpgD",
	"FWsSavxb48sr2UhjV0LlVtMqMyaEnnI24CDErRYMORuAEHH4sKFNkzLXhA7qPgQgCR1sVgSFJ57CelDo",
	"YRWXkEziICb/AoR1l5IFK64Q0SvKrumtiBmPXWP/ZliuiF5C0VrMUIXNziBdwqEXsTSVe4qJjpiJiPEo",
	"jSNTacypKquHBQSEQlF3vzBuT/LYKMjrAwhrzRpnjmURgxj5FHoU90xCZrMrCsdn4/9z/uX8+1kBv7Hr",
	"NBx33jItxG684f512bB3up2O/3yz03GWPm/YPow39yroH7U9GZpl23wIfRwF8r622UHHOqdkYEDXQ6BI",
	"gFQ6QPfzzXI1FejiMSaBDt4JRW+PLlB93KgnE2lhuzPH3Mo0LeSKixlucFC7r7BTxh5GoZzUYv9GKgcl",
	"YZlrEgSoBygSxpmJSeBU4piixVqPTVbzxzLGKAYNc7TYRwPTQauqSCAzUmFV5B1CfeJhaazZMhtvVmqn",
	"3ZWpByHwAMpWH0YjTG2l3TQHxUDEA2acwobbbC1wXOxPiinqu//9eu9//usftU7kulue/heeb2yi7s8/",
	"xTr0hAaTJDM8xzGSjEBIPArLIP1Ayeca+nBxgNJuRi4Ur8RwX2OBAiwkikLt9BY0f0So3G4thqNoCopd",
	"8rudULOW25M87GVc8D7qgXJpyaBcMxC/NES+SodVzEccg1Qe8BmmAyiJPz3i818C5l2VcmJAhNbFB+3D",
	"M9TT3ZRK0SGEeUmZ1Pk1RdfU4cwxxMbe7qXSBzeN2ta003E2b7am2Yt60qyEq9k1P7cuXbvZ3SzVIMtd",
	"1BkhzOHWVZRIckYLaF1E/h0TMpd+9gtKZciEtBsvoO83m14ZnJwF5SkOUSmvkEhsny3Y1MRrr4TKhw/t",
	"w8ScKMiLCnIbtlvNprdlbzdfgP3CfYntnvcK2z2/ubXlgvsSXsIyFGOtq3YhCNTMNBop6punOOMVBlib",
	"GMWKwJVApEKo+6/Sp+YcSa1YJkszWeE5oizUdsalz8S3gjzNKtNSXzRWPqk2cHJ0Ob/Yv/hw/ql9fNg+",
	"2L9onxx/+nB8fnp00H7TPjq0aiXtR2dnJ2elLe3jT6dnJ2/Pjs7Py9sPfz0qI/ZKvZtjwLIkpklQ6HCq",
	"iNXByfFhO0bq/fHJ78cZWFnT2dH+4b/KGo5PLha2nZ6dfGyft0+O28dvyyf97eSjalvNWxp/sSDtWbA4",
	"FfhhuX8XhyL26uzOY6Ra9oOAXQvlL6ngiCERgkf6E4RTRT+XgWHKwcJSYm9o0jA4Ca+Qx0Gnka6JHM64",
	"qhdDEMkUTyF/Y1SUDZ8lUOOBWj6MmFW779ROTJvY6K5S8zO9s/HGwkfm6KqQzr6xcEjStH1BvTrxYOez",
	"ffVKU3Tc6IHEKra9ItS3dq33F0MOIA5yxxAXWRg5Aol9LHEWmGTRgTJdscHJp4GSd1cymbhPBollEvpA",
	"8yDzVgJxjqnSFgHzcKBMkVWzGs2Xjuu4TsOqWa7+5Vrdqf6vjMA5hJNcvemUt0RXWyKncRWbYV8pAvW+",
	"u0pMCrLYcne2Z0OhueH6UGYxNMqNzFtGn3lXYFIGqqEMoNIjmgeKefd27Y2Nvd3cu7/UP4kfr72y5Lfu",
	"rmao3H/z+ebmnh7080a+5WczUeGV7lue1CxPmf5tSY2nlX4o45fuClv1KzEFNOHMGUNp0mKZEivLc+SS",
	"xfm1KmWkZycquPwlSWkmcXBkzvQXZB09FlFt3fT6SaYJqCQctOWrIQ4DzP0AhFD9QjwgNA1rqiQK50gd",
	"b0M5lcfFxpQsOa5quq1XK/XOymiogn0qT89R0wEVDFENEeoFkU/oAIXMR5j6SOl44kE+QpzPVITMX30Q",
	"UYhTlbkxM687sOToTc3lRZzIybkaY6Z8d3Fxqv72AHPgb5I9/ufvF1ZcFKLtn27N9lx5LuYwj8SiMctu",
	"RCCfeZFiR+RDn1AQJh+hwU2P6hJC/4YpHgBHTcdFZ0fnF2j/tO3o5IHU0VlJv5zg71pNp+E0FblYCBSH",
	"xNq1thzX2bK0GhpqVOsjkJx4+vcA5DzUb0GKUqgSiFDI2QjkEHQmSE+mgEyra9q+meW3eKGZsr2m665V",
	"AVRSBjhTjvc+Lp5axBzp8vVFFVZ5trB2L5W6xANhsjkGia7qUh83EzdtBf1wEKQnD8/yhXWllPrYzB0l",
	"5OszL8s0WFzBkDvjMKpMMsRBRpwWQ/o80HshHsA5+QKvm25SsvlnBHySVWwmPax8aWbqvjTddSooprVZ",
	"+NvUh89J+qFPuJAa+BzsqC111joYMSERDq7xRJikLqFKA/0RUU+ahG8caTxLQH6GNC7V0O9ErtvcZv2+",
	"APm6sYgapr2cFmsjrzaPcR+4rqrsJ4aHExAO6lhYeB1L69GOHqgekiP69By/3UeUUV0CaQI2An4tHUwM",
	"qZwO7dDzKAwZVzFZn0Dgi90OtZFCS/2dcxHUy2K5i3pTrO3p0IyyJnwVHlBlAealQDAu8wii3kQvrp8n",
	"ai/TwYYmSpEpHGe3TDf+Mnnd0VuCNJ7GS4+3YXblc8ZjBTa79PyiuYMCkyymLG7I09epBlsC112Iko1e",
	"iyqGXSxjikq42PQusPGcTzkL7BsSxOemOXixEkQWn87pDgnXPBrTjaJAkjCAT2b9eSrHcPUmaXJC0yjV",
	"FyGHPvmMOlafsY6FGDdN71PokGB9ea1lr+E0XzovFjKAWSrehdd9xp6jk7Mcnp9i2/x63NQTGRYRhA5S",
	"+D+pxT8JwNwbfjKgLUQpPcu+HjIBKXoxQkMsUJ+x6rAugoZFchVAb1Ia69LmPJ1julan2RLGjbd4Gd92",
	"7+helKboqpfM5Cs8v5b4ZK6QIYWoW1qqVuZutaq4WzM3NO7DS0v8stRh6k7nXKay2bMu9fIrL4qRQiZK",
	"DMqBTm2KLNk578OdMlF04uLyuV+YqbO5l3L3fMXgdP46TNNtPIRf/YQ2esYDr4usrKuqJ26GkC/gx7qL",
	"5Iq4lvjlSQXZHZVNle2NV/qeJG92Y2+U+p+aDQ1AlpzVHer3omB9zKj5jTR9s708NvmymY1szS9yJ3q3",
	"zIyrhuXuUj3YJi0P84vkWyNWLafjvQtE7gbOfcvEE9qjexGkWv7aZhLRhlgOM4+KJpu26BbmOkn1W5xC",
	"LhL2elbLUiE1FQ9+JlA2TMUjoLQ6kcJ4oosUwhwXv8+t/YAMPVPlc//c3KgybOa26d8uBnniP1VJSDJd",
	"S0XBFLnFxWwl4XX5Bel4J8zh7jJwMnx+0XloZKro/vn7hSmkyzv/JnFdVfSyeoTvRwvVrDAq0TAfdGGg",
	"mDWKhkIlfn80o0nim10PGgDEa0yLoZyi4LRceZUEmTF6QXbdJi6JRCLyPBCiHwXBxPkWbOsCpk9vxvzg",
	"+XKe1wSqwPLHmpC35/i73UyaO+ecri0EGtHvVwbqN+pP279lvKXJh5I5qkVfmmV0Ba5v3Wa3EBHxZf5v",
	"cbO+o2CgAON2C17uvOxv236v2bRbrRdg97bdbbvVbL7yW/2G1+z5C/DIWGkRJnlgb7p7ptKov2+/6d68",
	"mtob+efW1E4K05NXjeb0ctrdW4BCkVl/jy/j6E+9KChQn3EPkJ8TIfAHoDl58VlluYzu6bleq3kXnFjq",
	"DuUHln0ciKy+t8dYAJgu8QvztX0/rGRsJUs0YFrqutpY5gosH9BDLFZNlZnE5nIlm17IMxYxvQ1OBMKe",
	"B6H5YMrXpGr1h2iqjJ/7Wk1lk2okNHnj67TV8lRGQm7TV5c4ZF9g6k2WWNViCkP3Oiis+73l5R7PlH6d",
	"ZirR8UP9RZUvd6j+imeIr7UsYM138TJfde2XQQIdDMG7yiQ+vTq7+twp7VooASun2EU67YoSsHn/YqDW",
	"YzSY5O/+Zjq8uHTR20gh3IuHLXMtEkdiLeeidk8lbBmk32cNWyn+33QR2+MVm2W0fYLVZouAe4Rys4V0",
	"eRL1ZrevC0tVY6XCsOQLA2PXcZ3m1kIalReDpRVgZvQdK8DS1eISsBSTpTVgy2C8tyKwIlEXVIEtgeTv",
	"LQOreglFX9P4Js+hUeaBPHxNVXsUauWUc3rKKqryTtFDxMurA+WnVFPVcneqDMt9A/eh2WTWJU4yRzlz",
	"eV8B2O2/fXTHLNNjfy+pQgaKiEzbYlHq9ZenotK9U/Q7TN35hxCt0puAFU9nvjFlukhKYtegQiCZ9NQs",
	"n7oAIyy9ofLdsP50I/GiAPOiHV4Rayo2+JhA8YAWNH8B8ofx/KH0Fuen5oTkJub9SseTOAmjvMWKMDmQ",
	"LBOCJ1oW+vQM/7Ki0pJNWCP9tXQ33Afz/H6opB8qaVWGImbLWXzX/VplCR3GOYavcDRw9w8Udmey3skV",
	"+MvuNEuAzym+RGxF/n9nMsIUD5QX4mXXX2K00pOYeVqumGumrFc7PsknhubXyZeQrr3U7JnnPPw5Sao6",
	"uzcE7yr5Gqc5MUm/4Gi45+C39EglW7Bw4jDtTv8/AAD//xHKzcy8ZwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
