// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9a1fbuLZ/Rddn1ip0YscJKS3c1cVlgLY5nQEu0M49h+R0KfZOosGRPJIcmjL573dJ",
	"8jNxEofX0Md8KLH12ntrv7XlubE8NgoZBSqFtXtjhZjjEUjg+mnfk2QMp5z9AZ5s++8A+8BVA3zGozAA",
	"a9fafvECb7/aadqt5ivXbnlbL+2dl72GvdVobDew5/Z2dsCqWYRau9bQjK9ZFI/UWDN9aKYnvlWzOPwZ",
	"EQ6+tSt5BDVLeEMYYbVin/ERltauFUW6p5yEagohOaEDazqdqsEiZFSABr3luvYv2D+DPyMQUr3xGJVA",
	"9U8chgHxsCSM1v8QjKp32VI/cehbu9Y/6hlp6qZV1E856wUwOgSJSSDMuj4Ij5NQzWbtWic9hQ0iFIV4",
	"EjDsIyIQZRKFnIXAgwlSqEQBluAjxnUTB/MoGZJDQCOQQ+Y71rRmtdyG/YHiSA4ZJ18UYR4Nkf1IDoHK",
	"eHpEqNkC/VugERGC0IHCgNAxDkgCb8s+ZvINi+hjwnrMEAfBIu6BAq6vlkdYamp+OGvHoO3YB4z2A+I9",
	"Jj/EHIg8FgW+3u0eKF7wQAjwFZ8oIL2Ic6ASCYklINbXLxOUNPgvXNduUwmc4uAc+Bj4EeeMPyImF0MN",
	"+Jj4wBWVY5iDCYoo7gWg2HeIqa9+aegN4n6kW7BiIQM+Ag25Rqqh2KWtlMkIqHxUBr/IgFSiGAJPuVtt",
	"E8mAciw1Op5ZLXwQREICN5O3aZ9p3akFXBKjgBQSnAWnAaZwBtifrAL4LVDgxDuXWEZCEYfQPsdC8siT",
	"Eb/lHFdRDzgFCeIjcEEMAWd0Z80KcA8CkWtiWonpJtIHb+IFcDrEAtZe32j6kiUp8+Ed4EAO15+T+YbE",
	"RMJIrBp+zHzQOzStWSP8uW3GNFzXTY0I5hxPVHvC3fFa6wImYRQqRV6C8LQ2T9qYiX6wz+Ozz/9GmEoi",
	"JwVfpqEZhIyikeaPmjUi1DxlrKJU2AD4nZllCT/8mlKzyBEZlbHvE6WpcHBa6FGirrFUKle5HFon6znQ",
	"GAcRCAfpldAVTJJ+AmEOSFtz7Y9ggULMZWaPjEY3Sl45ciP8+VegA7UL21s1K57G2rX+89Nf/7nE9pd9",
	"+9+uvdPNfjp293mu4ad5V25WTRt6aMiuYFLXwKMQEy6QHGKJKBjPyWPaQ9FWSMpQ7NbrGfs6hNV95om6",
	"x6gHoRR1NgY+JnBdv2b8itCBfU3k0Da7IeqG2PV/iAmV+LONqW97Q8yxJ4HbAqRVy/jmxvKpcETUc3w2",
	"woTWr2BiN61dS4NqNx01s+MzKayapdoaaVvDmmeEacYK5yF4XwEjOD844UE4IdN/D0Pd9Q2pZsgKhjRv",
	"CVfCruDbuLTjX8+TV5t7G52Os7TD5vMSvKb5MPIyRrK7WN+eR6MR5pN5OYPEv54XJxqNesCVOHhmkpgD",
	"FWsSavxb48sr2UhjV0LlVtMqMyaEnnI24CDErRYMORuAEHH4sKFNkzLXhA7qPgQgCR1sVgSFJ57CelDo",
	"YRWXkEziICb/AoR1l5IFK64Q0SvKrumtiBmPXWP/ZliuiF5C0VrMUIXNziBdwqEXsTSVe4qJjpiJiPEo",
	"jSNTacypKquHBQSEQlF3vzBuT/LYKMjrAwhrzRpnjmURgxj5FHoU90xCZrMrCsdn4/9z/uX8+1kBv7Hr",
	"NBx33jItxG684f512bB3up2O/3yz03GWPm/YPow39yroH7U9GZpl23wIfRwF8r622UHHOqdkYEDXQ6BI",
	"gFQ6QPfzzXI1FejiMSaBDt4JRW+PLlB93KgnE2lhuzPH3Mo0LeSKixlucFC7r7BTxh5GoZzUYv9GKgcl",
	"YZlrEgSoBygSxpmJSeBU4piixVqPTVbzxzLGKAYNc7TYRwPTQauqSCAzUmFV5B1CfeJhaazZMhtvVmqn",
	"3ZWpByHwAMpWH0YjTG2l3TQHxUDEA2acwobbbC1wXOxPiinqu//9eu9//usftU7kulue/heeb2yi7s8/",
	"xTr0hAaTJDM8xzGSjEBIPArLIP1Ayeca+nBxgNJuRi4Ur8RwX2OBAiwkikLt9BY0f0So3G4thqNoCopd",
	"8rudULOW25M87GVc8D7qgXJpyaBcMxC/NES+SodVzEccg1Qe8BmmAyiJPz3i818C5l2VcmJAhNbFB+3D",
	"M9TT3ZRK0SGEeUmZ1Pk1RdfU4cwxxMbe7qXSBzeN2ta003E2b7am2Yt60qyEq9k1P7cuXbvZ3SzVIMtd",
	"1BkhzOHWVZRIckYLaF1E/h0TMpd+9gtKZciEtBsvoO83m14ZnJwF5SkOUSmvkEhsny3Y1MRrr4TKhw/t",
	"w8ScKMiLCnIbtlvNprdlbzdfgP3CfYntnvcK2z2/ubXlgvsSXsIyFGOtq3YhCNTMNBop6punOOMVBlib",
	"GMWKwJVApEKo+6/Sp+YcSa1YJkszWeE5oizUdsalz8S3gjzNKtNSXzRWPqk2cHJ0Ob/Yv/hw/ql9fNg+",
	"2L9onxx/+nB8fnp00H7TPjq0aiXtR2dnJ2elLe3jT6dnJ2/Pjs7Py9sPfz0qI/ZKvZtjwLIkpklQ6HCq",
	"iNXByfFhO0bq/fHJ78cZWFnT2dH+4b/KGo5PLha2nZ6dfGyft0+O28dvyyf97eSjalvNWxp/sSDtWbA4",
	"FfhhuX8XhyL26uzOY6Ra9oOAXQvlL6ngiCERgkf6E4RTRT+XgWHKwcJSYm9o0jA4Ca+Qx0Gnka6JHM64",
	"qhdDEMkUTyF/Y1SUDZ8lUOOBWj6MmFW779ROTJvY6K5S8zO9s/HGwkfm6KqQzr6xcEjStH1BvTrxYOez",
	"ffVKU3Tc6IHEKra9ItS3dq33F0MOIA5yxxAXWRg5Aol9LHEWmGTRgTJdscHJp4GSd1cymbhPBollEvpA",
	"8yDzVgJxjqnSFgHzcKBMkVWzGs2Xjuu4TsOqWa7+5Vrdqf6vjMA5hJNcvemUt0RXWyKncRWbYV8pAvW+",
	"u0pMCrLYcne2Z0OhueH6UGYxNMqNzFtGn3lXYFIGqqEMoNIjmgeKefd27Y2Nvd3cu7/UP4kfr72y5Lfu",
	"rmao3H/z+ebmnh7080a+5WczUeGV7lue1CxPmf5tSY2nlX4o45fuClv1KzEFNOHMGUNp0mKZEivLc+SS",
	"xfm1KmWkZycquPwlSWkmcXBkzvQXZB09FlFt3fT6SaYJqCQctOWrIQ4DzP0AhFD9QjwgNA1rqiQK50gd",
	"b0M5lcfFxpQsOa5quq1XK/XOymiogn0qT89R0wEVDFENEeoFkU/oAIXMR5j6SOl44kE+QpzPVITMX30Q",
	"UYhTlbkxM687sOToTc3lRZzIybkaY6Z8d3Fxqv72AHPgb5I9/ufvF1ZcFKLtn27N9lx5LuYwj8SiMctu",
	"RCCfeZFiR+RDn1AQJh+hwU2P6hJC/4YpHgBHTcdFZ0fnF2j/tO3o5IHU0VlJv5zg71pNp+FsKXKxECgO",
	"ibVrbTmus2VpNTTUqNZHIDnx9O8ByHmo34IUpVAlEKGQsxHIIehMkJ5MAZlW17R9M8tv8UIzZXtN112r",
	"AqikDHCmHO99XDy1iDnS5euLKqzybGHtXip1iQfCZHMMEl3VpT5uJm7aCvrhIEhPHp7lC+tKKfWxmTtK",
	"yNdnXpZpsLiCIXfGYVSZZIiDjDgthvR5oPdCPIBz8gVeN92kZPPPCPgkq9hMelj50szUfWm661RQTGuz",
	"8LepD5+T9EOfcCE18DnYUVvqrHUwYkIiHFzjiTBJXUKVBvojop40Cd840niWgPwMaVyqod+JXLe5zfp9",
	"AfJ1YxE1THs5LdZGXm0e4z5wXVXZTwwPJyAc1LGw8DqW1qMdPVA9JEf06Tl+u48oo7oE0gRsBPxaOpgY",
	"Ujkd2qHnURgyrmKyPoHAF7sdaiOFlvo75yKol8VyF/WmWNvToRllTfgqPKDKAsxLgWBc5hFEvYleXD9P",
	"1F6mgw1NlCJTOM5umW78ZfK6o7cEaTyNlx5vw+zK54zHCmx26flFcwcFJllMWdyQp69TDbYErrsQJRu9",
	"FlUMu1jGFJVwseldYOM5n3IW2DckiM9Nc/BiJYgsPp3THRKueTSmG0WBJGEAn8z681SO4epN0uSEplGq",
	"L0IOffIZdaw+Yx0LMW6a3qfQIcH68lrLXsNpvnReLGQAs1S8C6/7jD1HJ2c5PD/Ftvn1uKknMiwiCB2k",
	"8H9Si38SgLk3/GRAW4hSepZ9PWQCUvRihIZYoD5j1WFdBA2L5CqA3qQ01qXNeTrHdK1OsyWMG2/xMr7t",
	"3tG9KE3RVS+ZyVd4fi3xyVwhQwpRt7RUrczdalVxt2ZuaNyHl5b4ZanD1J3OuUxls2dd6uVXXhQjhUyU",
	"GJQDndoUWbJz3oc7ZaLoxMXlc78wU2dzL+Xu+YrB6fx1mKbbeAi/+glt9IwHXhdZWVdVT9wMIV/Aj3UX",
	"yRVxLfHLkwqyOyqbKtsbr/Q9Sd7sxt4o9T81GxqALDmrO9TvRcH6mFHzG2n6Znt5bPJlMxvZml/kTvRu",
	"mRlXDcvdpXqwTVoe5hfJt0asWk7HexeI3A2c+5aJJ7RH9yJItfy1zSSiDbEcZh4VTTZt0S3MdZLqtziF",
	"XCTs9ayWpUJqKh78TKBsmIpHQGl1IoXxRBcphDkufp9b+wEZeqbK5/65uVFl2Mxt079dDPLEf6qSkGS6",
	"loqCKXKLi9lKwuvyC9LxTpjD3WXgZPj8ovPQyFTR/fP3C1NIl3f+TeK6quhl9QjfjxaqWWFUomE+6MJA",
	"MWsUDYVK/P5oRpPEN7seNACI15gWQzlFwWm58ioJMmP0guy6TVwSiUTkeSBEPwqCifMt2NYFTJ/ejPnB",
	"8+U8rwlUgeWPNSFvz/F3u5k0d845XVsINKLfrwzUb9Sftn/LeEuTDyVzVIu+NMvoClzfus1uISLiy/zf",
	"4mZ9R8FAAcbtFrzcednftv1es2m3Wi/A7m2723ar2Xzlt/oNr9nzF+CRsdIiTPLA3nT3TKVRf99+0715",
	"NbU38s+tqZ0UpievGs3p5bS7twCFIrP+Hl/G0Z96UVCgPuMeID8nQuAPQHPy4rPKchnd03O9VvMuOLHU",
	"HcoPLPs4EFl9b4+xADBd4hfma/t+WMnYSpZowLTUdbWxzBVYPqCHWKyaKjOJzeVKNr2QZyxiehucCIQ9",
	"D0LzwZSvSdXqD9FUGT/3tZrKJtVIaPLG12mr5amMhNymry5xyL7A1JsssarFFIbudVBY93vLyz2eKf06",
	"zVSi44f6iypf7lD9Fc8QX2tZwJrv4mW+6tovgwQ6GIJ3lUl8enV29blT2rVQAlZOsYt02hUlYPP+xUCt",
	"x2gwyd/9zXR4cemit5FCuBcPW+ZaJI7EWs5F7Z5K2DJIv88atlL8v+kitscrNsto+wSrzRYB9wjlZgvp",
	"8iTqzW5fF5aqxkqFYckXBsau4zrNrYU0Ki8GSyvAzOg7VoClq8UlYCkmS2vAlsF4b0VgRaIuqAJbAsnf",
	"WwZW9RKKvqbxTZ5Do8wDefiaqvYo1Mop5/SUVVTlnaKHiJdXB8pPqaaq5e5UGZb7Bu5Ds8msS5xkjnLm",
	"8r4CsNt/++iOWabH/l5ShQwUEZm2xaLU6y9PRaV7p+h3mLrzDyFapTcBK57OfGPKdJGUxK5BhUAy6alZ",
	"PnUBRlh6Q+W7Yf3pRuJFAeZFO7wi1lRs8DGB4gEtaP4C5A/j+UPpLc5PzQnJTcz7lY4ncRJGeYsVYXIg",
	"WSYET7Qs9OkZ/mVFpSWbsEb6a+luuA/m+f1QST9U0qoMRcyWs/iu+7XKEjqMcwxf4Wjg7h8o7M5kvZMr",
	"8JfdaZYAn1N8idiK/P/OZIQpHigvxMuuv8RopScx87RcMddMWa92fJJPDM2vky8hXXup2TPPefhzklR1",
	"dm8I3lXyNU5zYpJ+wdFwz8Fv6ZFKtmDhxGHanf5/AAAA//9k23G2vGcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
