---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-edge-orchestrator-intel-com-v1alpha1-clustertemplate
  failurePolicy: Fail
  name: vclustertemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - edge-orchestrator.intel.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustertemplates
  sideEffects: None
