---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusterclasses
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanetemplates
  - rke2controlplanetemplates
  - kthreescontrolplanes
  - kthreescontrolplanetemplates  
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - edge-orchestrator.intel.com
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge-orchestrator.intel.com
  resources:
  - clustertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - edge-orchestrator.intel.com
  resources:
  - clustertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockerclustertemplates
  - dockermachinetemplates
  - intelclustertemplates
  - intelmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - watch
