# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: cluster-template-crd
description: A Helm chart for the ClusterTemplate CRD
type: application
version: 2.2.9-dev-7a2be595
appVersion: 2.2.9-dev-7a2be595
annotations:
  revision: 7a2be5952f3619b5739bccad1020416fc7c5b6ef
  created: "2026-03-30T13:49:19Z"
