# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: cluster-template-crd
description: A Helm chart for the ClusterTemplate CRD
type: application
version: 2.2.14
appVersion: 2.2.14
annotations:
  revision: 3b43ecf9ce397111ffb53ef68175703356a60862
  created: "2026-05-22T18:10:19Z"
