# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: cluster-template-crd
description: A Helm chart for the ClusterTemplate CRD
type: application
version: 2.2.12-dev
appVersion: 2.2.12-dev
annotations:
  revision: 783ee1b426f259e73b6f72459c380dd4dce0a3c4
  created: "2026-04-30T12:08:24Z"
