// Code generated by mockery v2.52.2. DO NOT EDIT.

package k8s

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// MockResourceInterface is an autogenerated mock type for the ResourceInterface type
type MockResourceInterface struct {
	mock.Mock
}

type MockResourceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceInterface) EXPECT() *MockResourceInterface_Expecter {
	return &MockResourceInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, name, obj, options, subresources
func (_m *MockResourceInterface) Apply(ctx context.Context, name string, obj *unstructured.Unstructured, options v1.ApplyOptions, subresources ...string) (*unstructured.Unstructured, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, obj, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions, ...string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, obj, options, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions, ...string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, obj, options, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions, ...string) error); ok {
		r1 = rf(ctx, name, obj, options, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockResourceInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - obj *unstructured.Unstructured
//   - options v1.ApplyOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Apply(ctx interface{}, name interface{}, obj interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Apply_Call {
	return &MockResourceInterface_Apply_Call{Call: _e.mock.On("Apply",
		append([]interface{}{ctx, name, obj, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Apply_Call) Run(run func(ctx context.Context, name string, obj *unstructured.Unstructured, options v1.ApplyOptions, subresources ...string)) *MockResourceInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(*unstructured.Unstructured), args[3].(v1.ApplyOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Apply_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_Apply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Apply_Call) RunAndReturn(run func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions, ...string) (*unstructured.Unstructured, error)) *MockResourceInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function with given fields: ctx, name, obj, options
func (_m *MockResourceInterface) ApplyStatus(ctx context.Context, name string, obj *unstructured.Unstructured, options v1.ApplyOptions) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, name, obj, options)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, obj, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, obj, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, name, obj, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type MockResourceInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - obj *unstructured.Unstructured
//   - options v1.ApplyOptions
func (_e *MockResourceInterface_Expecter) ApplyStatus(ctx interface{}, name interface{}, obj interface{}, options interface{}) *MockResourceInterface_ApplyStatus_Call {
	return &MockResourceInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, name, obj, options)}
}

func (_c *MockResourceInterface_ApplyStatus_Call) Run(run func(ctx context.Context, name string, obj *unstructured.Unstructured, options v1.ApplyOptions)) *MockResourceInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*unstructured.Unstructured), args[3].(v1.ApplyOptions))
	})
	return _c
}

func (_c *MockResourceInterface_ApplyStatus_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_ApplyStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_ApplyStatus_Call) RunAndReturn(run func(context.Context, string, *unstructured.Unstructured, v1.ApplyOptions) (*unstructured.Unstructured, error)) *MockResourceInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, obj, options, subresources
func (_m *MockResourceInterface) Create(ctx context.Context, obj *unstructured.Unstructured, options v1.CreateOptions, subresources ...string) (*unstructured.Unstructured, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.CreateOptions, ...string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, obj, options, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.CreateOptions, ...string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, obj, options, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured, v1.CreateOptions, ...string) error); ok {
		r1 = rf(ctx, obj, options, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockResourceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *unstructured.Unstructured
//   - options v1.CreateOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Create(ctx interface{}, obj interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Create_Call {
	return &MockResourceInterface_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, obj, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Create_Call) Run(run func(ctx context.Context, obj *unstructured.Unstructured, options v1.CreateOptions, subresources ...string)) *MockResourceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured), args[2].(v1.CreateOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Create_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Create_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured, v1.CreateOptions, ...string) (*unstructured.Unstructured, error)) *MockResourceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, options, subresources
func (_m *MockResourceInterface) Delete(ctx context.Context, name string, options v1.DeleteOptions, subresources ...string) error {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions, ...string) error); ok {
		r0 = rf(ctx, name, options, subresources...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResourceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockResourceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options v1.DeleteOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Delete(ctx interface{}, name interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Delete_Call {
	return &MockResourceInterface_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, name, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Delete_Call) Run(run func(ctx context.Context, name string, options v1.DeleteOptions, subresources ...string)) *MockResourceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Delete_Call) Return(_a0 error) *MockResourceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceInterface_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions, ...string) error) *MockResourceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, options, listOptions
func (_m *MockResourceInterface) DeleteCollection(ctx context.Context, options v1.DeleteOptions, listOptions v1.ListOptions) error {
	ret := _m.Called(ctx, options, listOptions)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, options, listOptions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResourceInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockResourceInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - options v1.DeleteOptions
//   - listOptions v1.ListOptions
func (_e *MockResourceInterface_Expecter) DeleteCollection(ctx interface{}, options interface{}, listOptions interface{}) *MockResourceInterface_DeleteCollection_Call {
	return &MockResourceInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, options, listOptions)}
}

func (_c *MockResourceInterface_DeleteCollection_Call) Run(run func(ctx context.Context, options v1.DeleteOptions, listOptions v1.ListOptions)) *MockResourceInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *MockResourceInterface_DeleteCollection_Call) Return(_a0 error) *MockResourceInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *MockResourceInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, options, subresources
func (_m *MockResourceInterface) Get(ctx context.Context, name string, options v1.GetOptions, subresources ...string) (*unstructured.Unstructured, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions, ...string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, options, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions, ...string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, options, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions, ...string) error); ok {
		r1 = rf(ctx, name, options, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockResourceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options v1.GetOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Get(ctx interface{}, name interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Get_Call {
	return &MockResourceInterface_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, name, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Get_Call) Run(run func(ctx context.Context, name string, options v1.GetOptions, subresources ...string)) *MockResourceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Get_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions, ...string) (*unstructured.Unstructured, error)) *MockResourceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockResourceInterface) List(ctx context.Context, opts v1.ListOptions) (*unstructured.UnstructuredList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *unstructured.UnstructuredList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*unstructured.UnstructuredList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *unstructured.UnstructuredList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.UnstructuredList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockResourceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *MockResourceInterface_Expecter) List(ctx interface{}, opts interface{}) *MockResourceInterface_List_Call {
	return &MockResourceInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockResourceInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *MockResourceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *MockResourceInterface_List_Call) Return(_a0 *unstructured.UnstructuredList, _a1 error) *MockResourceInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*unstructured.UnstructuredList, error)) *MockResourceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, options, subresources
func (_m *MockResourceInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, options v1.PatchOptions, subresources ...string) (*unstructured.Unstructured, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, pt, data, options, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, pt, data, options, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, options, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockResourceInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - options v1.PatchOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Patch_Call {
	return &MockResourceInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, options v1.PatchOptions, subresources ...string)) *MockResourceInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Patch_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*unstructured.Unstructured, error)) *MockResourceInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, obj, options, subresources
func (_m *MockResourceInterface) Update(ctx context.Context, obj *unstructured.Unstructured, options v1.UpdateOptions, subresources ...string) (*unstructured.Unstructured, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions, ...string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, obj, options, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions, ...string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, obj, options, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions, ...string) error); ok {
		r1 = rf(ctx, obj, options, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockResourceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *unstructured.Unstructured
//   - options v1.UpdateOptions
//   - subresources ...string
func (_e *MockResourceInterface_Expecter) Update(ctx interface{}, obj interface{}, options interface{}, subresources ...interface{}) *MockResourceInterface_Update_Call {
	return &MockResourceInterface_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, obj, options}, subresources...)...)}
}

func (_c *MockResourceInterface_Update_Call) Run(run func(ctx context.Context, obj *unstructured.Unstructured, options v1.UpdateOptions, subresources ...string)) *MockResourceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured), args[2].(v1.UpdateOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockResourceInterface_Update_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Update_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured, v1.UpdateOptions, ...string) (*unstructured.Unstructured, error)) *MockResourceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, obj, options
func (_m *MockResourceInterface) UpdateStatus(ctx context.Context, obj *unstructured.Unstructured, options v1.UpdateOptions) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, obj, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, obj, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions) *unstructured.Unstructured); ok {
		r0 = rf(ctx, obj, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, obj, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockResourceInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *unstructured.Unstructured
//   - options v1.UpdateOptions
func (_e *MockResourceInterface_Expecter) UpdateStatus(ctx interface{}, obj interface{}, options interface{}) *MockResourceInterface_UpdateStatus_Call {
	return &MockResourceInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, obj, options)}
}

func (_c *MockResourceInterface_UpdateStatus_Call) Run(run func(ctx context.Context, obj *unstructured.Unstructured, options v1.UpdateOptions)) *MockResourceInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *MockResourceInterface_UpdateStatus_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockResourceInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured, v1.UpdateOptions) (*unstructured.Unstructured, error)) *MockResourceInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *MockResourceInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockResourceInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *MockResourceInterface_Expecter) Watch(ctx interface{}, opts interface{}) *MockResourceInterface_Watch_Call {
	return &MockResourceInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *MockResourceInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *MockResourceInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *MockResourceInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *MockResourceInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceInterface_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *MockResourceInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceInterface creates a new instance of MockResourceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceInterface {
	mock := &MockResourceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
