package k8s

// This extra code augments the code generated by mockery.
// Maybe allows a mocked method call to be optional.
// It is needed for fuzz testing.
func (_c *MockResourceInterface_List_Call) Maybe() *MockResourceInterface_List_Call {
	_c.Call.Maybe()
	return _c
}
