{
 "title": "Cluster Orch - Cluster Manager",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cluster_manager_http_response_codes_counter,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Manager instance timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (cluster_manager_http_response_codes_counter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP response time for instance ${instance}",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "cluster_manager_http_response_time_seconds_histogram_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "/v2/clusters/* response status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "cluster_manager_http_response_codes_counter{instance=\"$instance\", path=~\"/v2/clusters\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP response time for instance ${instance}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cluster_manager_http_response_time_seconds_histogram_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response codes counter for instance $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "cluster_manager_http_response_codes_counter{instance=\"$instance\"}",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}