// Code generated by mockery v2.53.0. DO NOT EDIT.

package dynamic

import (
	mock "github.com/stretchr/testify/mock"
	dynamic "k8s.io/client-go/dynamic"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function with given fields: resource
func (_m *MockInterface) Resource(resource schema.GroupVersionResource) dynamic.NamespaceableResourceInterface {
	ret := _m.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 dynamic.NamespaceableResourceInterface
	if rf, ok := ret.Get(0).(func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface); ok {
		r0 = rf(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.NamespaceableResourceInterface)
		}
	}

	return r0
}

// MockInterface_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type MockInterface_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - resource schema.GroupVersionResource
func (_e *MockInterface_Expecter) Resource(resource interface{}) *MockInterface_Resource_Call {
	return &MockInterface_Resource_Call{Call: _e.mock.On("Resource", resource)}
}

func (_c *MockInterface_Resource_Call) Run(run func(resource schema.GroupVersionResource)) *MockInterface_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.GroupVersionResource))
	})
	return _c
}

func (_c *MockInterface_Resource_Call) Return(_a0 dynamic.NamespaceableResourceInterface) *MockInterface_Resource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterface_Resource_Call) RunAndReturn(run func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface) *MockInterface_Resource_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
