# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch: 

jobs:
  post-merge:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_build: true
      run_version_check: true
      run_dep_version_check: true
      cache_go: true
      run_lint: true
      run_test: true
      run_version_tag: true
      remove_cache_go: true
      run_docker_build: true
      run_docker_push: true
      run_helm_build: true
      run_helm_push: true
    secrets: inherit
