# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch: 
permissions: {}
jobs:
  post-merge:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@f341738d975c38b2b91f25d405baeb2d39bf2ddb  # 0.1.9
    with:
      run_build: true
      run_version_check: true
      run_dep_version_check: true
      cache_go: true
      run_lint: true
      run_test: true
      run_version_tag: true
      remove_cache_go: true
      run_docker_build: true
      run_docker_push: true
      run_helm_build: true
      run_helm_push: true
    secrets: inherit  # zizmor: ignore[secrets-inherit]
